---
version: "3"
services:
  postgres:
    image: docker.io/postgres:15-alpine
    command: postgres -c 'max_connections=500'
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql

volumes:
  postgres_volume: {}
